create table service_user
(
    id bigint generated by default as identity
        constraint service_user_pkey
            primary key,
    email varchar(255) not null,
    password varchar(255) not null
);

alter table service_user owner to postgres;

create table account
(
    id bigint generated by default as identity
        constraint account_pkey
            primary key,
    name varchar(255) not null,
    user_id bigint not null
        constraint fk_account_service_user_id
            references service_user
            on delete set null
        constraint fk_transaction_to_account_id_account_id
            references account
            on delete set null,
    balance double precision not null
);

alter table account owner to postgres;

create table category
(
    id bigint generated by default as identity
        constraint category_pkey
            primary key,
    name varchar(255) not null
);

alter table category owner to postgres;

create table transaction
(
    id bigint generated by default as identity
        constraint transaction_pkey
            primary key,
    sum double precision not null,
    from_account_id bigint
        constraint fk_transaction_from_account_id_account_id
            references account
            on delete set null,
    to_account_id bigint,
    date date not null
);

alter table transaction owner to postgres;

create table transaction_category
(
    transaction_id bigint not null
        constraint fk_transaction_id
            references transaction
            on delete set null,
    category_id bigint not null
        constraint fk_category_id
            references category
            on delete set null
);

alter table transaction_category owner to postgres;

